---
AWSTemplateFormatVersion: "2010-09-09"

Description: Creates all resources needed to run a Gif Battle.

# Metadata:

# Parameters:

# Mappings:

# Conditions:

# Transform:

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
  Nacl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: VPC
  # NaclEntry:
  #   Type: AWS::EC2::NetworkAclEntry
  #   Properties:
  #     NetworkAclId:
  #       Ref: Nacl
  #     Protocol: 443
  #     RuleAction: allow
  #     RuleNumber: 100

Outputs:
  VPC:
    Value:
      Ref: VPC
    Description: Name of the VPC
  InternetGateway:
    Value:
      Ref: InternetGateway
    Description: Name of the Internet Gateway
  AttachInternetGateway:
    Value:
      Ref: AttachInternetGateway
    Description: Name of the internet gateway attachment
  
# aws cloudformation update-stack --stack-name test --template-body file://cloudformation.yaml --tags Key=Name,Value="Gif Battle"
# aws cloudformation delete-stack --stack-name test